---
jumpbox: dci-jumpbox
domain: dci.local
machine_network_cidr: 10.60.0.0/24
machine_network_ip: "{{ machine_network_cidr | nthhost(190) }}"
local_repo: /opt/dci

topics:
  - topic: RHEL-8.*
    # variants:
    #   - AppStream
    #   - BaseOS
    # archs:
    #   - x86_64
    # with_debug: false
    systems:
      - fqdn: "sut1.{{ domain }}"
        efi: true
      - fqdn: "sut2.{{ domain }}"
        efi: false

lab:
  provisioner_dir: /opt/dci-provisioner
  dns_server: "{{ machine_network_ip }}"
  router: "{{ machine_network_ip }}"
  dhcp_start: "{{ machine_network_cidr | ipaddr('20') | ipaddr('address') }}"
  dhcp_end: "{{ machine_network_cidr | ipaddr('100') | ipaddr('address') }}"

  # By default we will build a bridge for the virtual systems in this example
  # settings Uncomment and set the bridge_interface to your physical network
  # interface which will have your Systems Under Test's.  If you set your
  # network up outside of this you can set build_bridge to false.
  build_bridge: true
  #  bridge_interface: eno2
  #

  system_inventory:
    sut1:
      ip_address: 10.60.0.51
      mac: "52:54:00:EF:C0:2C"
      arch: x86_64
      power_address: "{{ jumpbox }}.{{ domain }}"
      power_user: admin
      power_password: password
      power_id: 6230
      power_type: ipmitool_lanplus
      virt:
        mode: efi
        disks:
          main: 150
        memory: "16384"
        vcpu: "4"

    sut2:
      ip_address: 10.60.0.52
      mac: "52:54:00:EF:C0:2D"
      arch: x86_64
      power_address: "{{ jumpbox }}.{{ domain }}"
      power_user: admin
      power_password: password
      power_id: 6231
      power_type: ipmitool_lanplus
      virt:
        mode: legacy
        disks:
          main: 150
        memory: "16384"
        vcpu: "4"

    ppc64le:
      ip_address: 10.60.0.53
      mac: 94:6d:ae:c5:35:be
      arch: ppc64le
      power_address: powercontrol.example.com
      power_user: PowerUser
      power_password: InsecurePassword
      power_id: SN3826325:lsh20143:4
      power_type: lpar
      boot_file: petitboot.cfg
